defaults: &defaults
  working_directory: ~/laborious
  docker:
    - image: circleci/node:10

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn start
  test:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
